# Generated by Django 5.1.1 on 2024-10-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('trip_id', models.CharField(max_length=10)),
                ('traveler_name', models.CharField(max_length=100)),
                ('traveler_number', models.CharField(max_length=10)),
                ('ticket_cost', models.FloatField()),
                ('traveler_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
